### ISSUE TITLE
Failing to open

### ISSUE THREAD

**Issue by rvlobato** [flathub/org.onionshare.OnionShare#14]
Version 2.6
The module named 'PySide2' is not found when trying to run.

> Traceback (most recent call last):
>   File "/app/bin/onionshare", line 5, in <module>
>     from onionshare import main
>   File "/app/lib/python3.10/site-packages/onionshare/__init__.py", line 29, in <module>
>     from PySide2 import QtCore, QtWidgets, QtGui
> ModuleNotFoundError: No module named 'PySide2'

**Comment by rvlobato** [comment]
It seems fixed in the last update
